name: zetoe
services:
  - name: api
    github:
      branch: main
      deploy_on_push: true
      repo: your-username/your-repo-name
    build_command: cd src/backend && poetry install && poetry run alembic upgrade head
    run_command: cd src/backend && uvicorn main:app --host 0.0.0.0 --port ${PORT}
    envs:
      - key: TAVILY_API_KEY
        value: ""
        type: SECRET
      - key: OPENAI_API_KEY
        value: ""
        type: SECRET
      - key: GROQ_API_KEY
        value: ""
        type: SECRET
    http_port: 8080
    instance_size_slug: basic-xxs
    instance_count: 1
    region: sfo
