services:
  - type: web
    name: nepaligpt
    runtime: python
    plan: free
    envVars:
      - key: TAVILY_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
    region: oregon
    buildCommand: poetry install && poetry run alembic upgrade head
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    rootDir: src/backend
version: "1"
